// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6-l3IDF220FK3bulio6I8gV7ib5ncUYc',
    appId: '1:310605546257:web:84fa445e91f20edc2542b0',
    messagingSenderId: '310605546257',
    projectId: 'todo-01-8cd48',
    authDomain: 'todo-01-8cd48.firebaseapp.com',
    storageBucket: 'todo-01-8cd48.firebasestorage.app',
    measurementId: 'G-JM031N657T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD72jzsVitccFJTynYLxuOv7hmgKt7n8wo',
    appId: '1:310605546257:android:9d662d19ec62085c2542b0',
    messagingSenderId: '310605546257',
    projectId: 'todo-01-8cd48',
    storageBucket: 'todo-01-8cd48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vaDQmQDNJNQkYCNHlAUJL9DqrP_eJM0',
    appId: '1:310605546257:ios:843f039c8714639c2542b0',
    messagingSenderId: '310605546257',
    projectId: 'todo-01-8cd48',
    storageBucket: 'todo-01-8cd48.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vaDQmQDNJNQkYCNHlAUJL9DqrP_eJM0',
    appId: '1:310605546257:ios:843f039c8714639c2542b0',
    messagingSenderId: '310605546257',
    projectId: 'todo-01-8cd48',
    storageBucket: 'todo-01-8cd48.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6-l3IDF220FK3bulio6I8gV7ib5ncUYc',
    appId: '1:310605546257:web:b89a9439db390f262542b0',
    messagingSenderId: '310605546257',
    projectId: 'todo-01-8cd48',
    authDomain: 'todo-01-8cd48.firebaseapp.com',
    storageBucket: 'todo-01-8cd48.firebasestorage.app',
    measurementId: 'G-Q0TSFRM725',
  );
}
